env: production
languageCode: en-us
title: Guillaume Schurck
description: Personal portfolio website
theme: PaperMod
googleAnalytics: G-0GDW3G85ZR

params:
  description: Personal portfolio website
  homeInfoParams:
    Title: Guillaume Schurck
    Content: "Developer with a passion for innovative technologies
    

    I like to create things.
    
    
    Check my projects â¬‡"
  profileMode:
    enabled: true
    defaultTheme: auto
    title: Guillaume Schurck # optional default will be site title
    subtitle: "Developer with a passion for innovative technologies
    

    I like to create things."
    imageUrl: https://avatars.githubusercontent.com/u/21091232
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Personal projects
        url: "/projects"
      #- name: Blog
      #  url: "/blog"
  socialIcons:
    - name: github
      url: "https://github.com/gschurck"
    - name: linkedin
      url: "https://www.linkedin.com/in/guillaume-schurck/"
    - name: twitter
      url: "https://twitter.com/gschurck"
  tocopen: true
  hideFooter: true
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: true
menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 10
    #- identifier: blog
    #  name: blog
    #  url: /blog/
    #  weight: 20
    #- identifier: about
    #  name: about
    #  url: https://example.org
    #  weight: 30